name: FireworkWarsLobby
version: '1.0-SNAPSHOT'
main: foundation.esoteric.fireworkwarslobby.FireworkWarsLobbyPlugin
api-version: '1.21.3'
website: "https://github.com/EsotericFoundation/firework-wars-lobby-plugin"
depend: [FireworkWarsCore]